require "user.plugins"
require "user.options"
require "user.keymaps"
require "user.nvim-tree"
require "user.telescope"
require "user.colorscheme"
require "user.dap"
-- require "user.toggleterm"
-- require "user.project"
-- require "user.alpha"
-- require "user.autocommands"
